-- Official rehearsals are presented to users as "公開リハ".  They deliberately
-- share the ticket-code round namespace with unofficial rehearsals.
CREATE TABLE IF NOT EXISTS public.rehearsal_round_names (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE CHECK (btrim(name) <> ''),
  sort_order integer NOT NULL UNIQUE
);
INSERT INTO public.rehearsal_round_names (name, sort_order)
VALUES ('第1回', 10), ('第2回', 20), ('第3回', 30), ('最終リハ', 40)
ON CONFLICT (name) DO NOTHING;

ALTER TABLE public.rehearsals
  DROP CONSTRAINT IF EXISTS rehearsals_official_values_check,
  ADD CONSTRAINT rehearsals_official_values_check CHECK (
    type <> 'official' OR (
      round_id IS NOT NULL AND start_time IS NOT NULL AND end_time IS NOT NULL
      AND capacity IS NOT NULL AND capacity > 0 AND end_time > start_time
      AND btrim(round_name) <> ''
    )
  );

CREATE UNIQUE INDEX IF NOT EXISTS rehearsals_official_class_round_name_key
  ON public.rehearsals (class_id, round_name) WHERE type = 'official';

-- A rehearsal round that has ever issued a ticket must never be recycled.
CREATE TABLE IF NOT EXISTS public.rehearsal_used_rounds (
  class_id smallint NOT NULL REFERENCES public.class_performances(id) ON DELETE CASCADE,
  round_id smallint NOT NULL CHECK (round_id BETWEEN 0 AND 15),
  PRIMARY KEY (class_id, round_id)
);
INSERT INTO public.rehearsal_used_rounds (class_id, round_id)
SELECT DISTINCT ct.class_id, ct.round_id
FROM public.class_tickets ct
JOIN public.tickets t ON t.id = ct.id
JOIN public.ticket_types tt ON tt.id = t.ticket_type
WHERE tt.name = 'クラス公演(リハーサル)'
ON CONFLICT DO NOTHING;

-- Keep the pre-existing自主リハ allocator in the same namespace as公開リハ.
CREATE OR REPLACE FUNCTION public.create_unofficial_rehearsal(
  p_class_id smallint, p_round_name text, p_start_time timestamptz,
  p_end_time timestamptz, p_capacity smallint
) RETURNS public.rehearsals
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_round smallint; v_result public.rehearsals;
BEGIN
  IF btrim(coalesce(p_round_name, '')) = '' THEN RAISE EXCEPTION 'リハーサル名を入力してください。'; END IF;
  IF p_start_time IS NULL OR p_start_time <= now() THEN RAISE EXCEPTION '開始時刻は未来の日時を指定してください。'; END IF;
  IF p_end_time IS NULL OR p_end_time <= p_start_time THEN RAISE EXCEPTION '終了時刻は開始時刻より後にしてください。'; END IF;
  IF p_capacity IS NULL OR p_capacity <= 0 THEN RAISE EXCEPTION '定員は1以上で指定してください。'; END IF;
  PERFORM pg_advisory_xact_lock(94117, p_class_id);
  SELECT n::smallint INTO v_round FROM generate_series(0, 15) n
  WHERE NOT EXISTS (SELECT 1 FROM public.rehearsals r WHERE r.class_id = p_class_id AND r.round_id = n)
    AND NOT EXISTS (SELECT 1 FROM public.rehearsal_used_rounds u WHERE u.class_id = p_class_id AND u.round_id = n)
  ORDER BY n LIMIT 1;
  IF v_round IS NULL THEN RAISE EXCEPTION '作成できるリハーサル回は1クラス16件までです。'; END IF;
  INSERT INTO public.rehearsals (class_id, round_id, round_name, start_time, end_time, capacity, type, is_active)
  VALUES (p_class_id, v_round, btrim(p_round_name), p_start_time, p_end_time, p_capacity, 'unofficial', true)
  RETURNING * INTO v_result;
  RETURN v_result;
END $$;

CREATE OR REPLACE FUNCTION public.create_official_rehearsal(
  p_class_id smallint, p_round_name text, p_start_time timestamptz,
  p_end_time timestamptz, p_capacity smallint
) RETURNS public.rehearsals
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_round smallint; v_result public.rehearsals;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.rehearsal_round_names WHERE name = btrim(coalesce(p_round_name, ''))) THEN
    RAISE EXCEPTION '公開リハの回名は有効な選択肢から選択してください。';
  END IF;
  IF p_start_time IS NULL OR p_start_time <= now() THEN RAISE EXCEPTION '開始時刻は未来の日時を指定してください。'; END IF;
  IF p_end_time IS NULL OR p_end_time <= p_start_time THEN RAISE EXCEPTION '終了時刻は開始時刻より後にしてください。'; END IF;
  IF p_capacity IS NULL OR p_capacity <= 0 THEN RAISE EXCEPTION '定員は1以上で指定してください。'; END IF;
  PERFORM pg_advisory_xact_lock(94117, p_class_id);
  SELECT n::smallint INTO v_round FROM generate_series(0, 15) n
  WHERE NOT EXISTS (SELECT 1 FROM public.rehearsals r WHERE r.class_id = p_class_id AND r.round_id = n)
    AND NOT EXISTS (SELECT 1 FROM public.rehearsal_used_rounds u WHERE u.class_id = p_class_id AND u.round_id = n)
  ORDER BY n LIMIT 1;
  IF v_round IS NULL THEN RAISE EXCEPTION '作成できるリハーサル回は1クラス16件までです。'; END IF;
  INSERT INTO public.rehearsals (class_id, round_id, round_name, start_time, end_time, capacity, type, is_active)
  VALUES (p_class_id, v_round, btrim(p_round_name), p_start_time, p_end_time, p_capacity, 'official', true)
  RETURNING * INTO v_result;
  RETURN v_result;
END $$;

CREATE OR REPLACE FUNCTION public.update_official_rehearsal(
  p_id smallint, p_round_name text, p_start_time timestamptz,
  p_end_time timestamptz, p_capacity smallint
) RETURNS public.rehearsals
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_result public.rehearsals;
BEGIN
  PERFORM 1 FROM public.rehearsals WHERE id = p_id AND type = 'official' AND is_active FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION '編集できる公開リハが見つかりません。'; END IF;
  IF (SELECT start_time <= now() FROM public.rehearsals WHERE id = p_id) THEN RAISE EXCEPTION '開始済みの公開リハは編集できません。'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.rehearsal_round_names WHERE name = btrim(coalesce(p_round_name, ''))) THEN RAISE EXCEPTION '公開リハの回名が不正です。'; END IF;
  IF p_start_time IS NULL OR p_start_time <= now() OR p_end_time IS NULL OR p_end_time <= p_start_time OR p_capacity IS NULL OR p_capacity <= 0 THEN RAISE EXCEPTION '入力内容が不正です。'; END IF;
  IF p_capacity < (SELECT active_ticket_count FROM public.rehearsals WHERE id = p_id) THEN RAISE EXCEPTION '現在有効なチケット数を下回る定員には変更できません。'; END IF;
  UPDATE public.rehearsals SET round_name = btrim(p_round_name), start_time = p_start_time, end_time = p_end_time, capacity = p_capacity WHERE id = p_id RETURNING * INTO v_result;
  RETURN v_result;
END $$;

CREATE OR REPLACE FUNCTION public.delete_or_deactivate_official_rehearsal(p_id smallint)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_class smallint; v_round smallint; v_issued boolean;
BEGIN
  SELECT class_id, round_id INTO v_class, v_round FROM public.rehearsals WHERE id = p_id AND type = 'official' FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION '操作できる公開リハが見つかりません。'; END IF;
  SELECT EXISTS (SELECT 1 FROM public.rehearsal_used_rounds WHERE class_id = v_class AND round_id = v_round) INTO v_issued;
  IF v_issued THEN UPDATE public.rehearsals SET is_active = false WHERE id = p_id; ELSE DELETE FROM public.rehearsals WHERE id = p_id; END IF;
  RETURN v_issued;
END $$;

-- The original RPC is shared by both kinds.  It locks the rehearsal row before
-- checking capacity, so parallel issuance cannot overbook it.
CREATE OR REPLACE FUNCTION public.issue_rehearsal_ticket_with_code(
  p_user_id uuid, p_ticket_type_id smallint, p_relationship_id smallint,
  p_class_id smallint, p_round_id smallint, p_issue_count smallint,
  p_codes text[], p_signatures text[]
) RETURNS TABLE(code text, signature text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_rehearsal public.rehearsals; v_ticket_id uuid; i integer; v_role text; v_mode text;
BEGIN
  IF p_relationship_id <> 1 THEN RAISE EXCEPTION 'リハーサルは本人分のみ発券できます。'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.ticket_types WHERE id = p_ticket_type_id AND name = 'クラス公演(リハーサル)') THEN RAISE EXCEPTION 'リハーサル用のチケット種別を指定してください。'; END IF;
  IF p_issue_count IS NULL OR p_issue_count <= 0 OR array_length(p_codes, 1) IS DISTINCT FROM p_issue_count OR array_length(p_signatures, 1) IS DISTINCT FROM p_issue_count THEN RAISE EXCEPTION '発券枚数またはチケット情報が不正です。'; END IF;
  SELECT * INTO v_rehearsal FROM public.rehearsals WHERE class_id = p_class_id AND round_id = p_round_id FOR UPDATE;
  IF NOT FOUND OR NOT v_rehearsal.is_active THEN RAISE EXCEPTION 'このリハーサルは中止または受付終了しています。'; END IF;
  IF now() >= v_rehearsal.start_time THEN RAISE EXCEPTION '開始時刻を過ぎたため発券できません。'; END IF;
  SELECT role INTO v_role FROM public.users WHERE id = p_user_id;
  IF v_role = 'junior' THEN RAISE EXCEPTION '中学生はリハーサルのチケットを取得できません。'; END IF;
  SELECT rehearsal_invite_mode INTO v_mode FROM public.ticket_issue_controls WHERE id = 1;
  IF (v_rehearsal.type = 'official' AND v_mode NOT IN ('open', 'public-rehearsals')) OR (v_rehearsal.type = 'unofficial' AND v_mode NOT IN ('open', 'self-rehearsals')) THEN RAISE EXCEPTION 'このリハーサルは現在発券できません。'; END IF;
  IF v_rehearsal.type = 'official' AND p_issue_count <> 1 THEN RAISE EXCEPTION '公開リハは1回につき1枚のみ発券できます。'; END IF;
  IF v_rehearsal.active_ticket_count + p_issue_count > v_rehearsal.capacity THEN RAISE EXCEPTION 'このリハーサルの残席が不足しています。'; END IF;
  FOR i IN 1..p_issue_count LOOP
    INSERT INTO public.tickets (user_id, ticket_type, relationship, status, code, signature, person_count) VALUES (p_user_id, p_ticket_type_id, p_relationship_id, 'valid', p_codes[i], p_signatures[i], 1) RETURNING id INTO v_ticket_id;
    INSERT INTO public.class_tickets (id, class_id, round_id) VALUES (v_ticket_id, p_class_id, p_round_id);
  END LOOP;
  RETURN QUERY SELECT unnest(p_codes), unnest(p_signatures);
END $$;

CREATE OR REPLACE FUNCTION public.count_new_rehearsal_ticket()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.tickets t JOIN public.ticket_types tt ON tt.id = t.ticket_type WHERE t.id = NEW.id AND t.status = 'valid' AND tt.name = 'クラス公演(リハーサル)') THEN
    INSERT INTO public.rehearsal_used_rounds (class_id, round_id) VALUES (NEW.class_id, NEW.round_id) ON CONFLICT DO NOTHING;
    UPDATE public.rehearsals SET active_ticket_count = active_ticket_count + 1 WHERE class_id = NEW.class_id AND round_id = NEW.round_id;
  END IF;
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.sync_rehearsal_active_ticket_count()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_class_id smallint; v_round_id smallint; v_delta integer := 0; v_ticket_type smallint;
BEGIN
  IF TG_OP = 'DELETE' THEN v_ticket_type := OLD.ticket_type; v_delta := CASE WHEN OLD.status = 'valid' THEN -1 ELSE 0 END; SELECT class_id, round_id INTO v_class_id, v_round_id FROM public.class_tickets WHERE id = OLD.id;
  ELSE v_ticket_type := NEW.ticket_type; IF OLD.status = NEW.status THEN RETURN NEW; END IF; v_delta := CASE WHEN NEW.status = 'valid' THEN 1 WHEN OLD.status = 'valid' THEN -1 ELSE 0 END; SELECT class_id, round_id INTO v_class_id, v_round_id FROM public.class_tickets WHERE id = NEW.id; END IF;
  IF EXISTS (SELECT 1 FROM public.ticket_types WHERE id = v_ticket_type AND name = 'クラス公演(リハーサル)') AND v_delta <> 0 AND v_class_id IS NOT NULL THEN UPDATE public.rehearsals SET active_ticket_count = greatest(active_ticket_count + v_delta, 0) WHERE class_id = v_class_id AND round_id = v_round_id; END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.prevent_late_rehearsal_ticket_cancellation()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_start timestamptz;
BEGIN
  IF OLD.status = 'valid' AND NEW.status = 'cancelled' THEN
    SELECT r.start_time INTO v_start FROM public.class_tickets ct JOIN public.rehearsals r ON r.class_id = ct.class_id AND r.round_id = ct.round_id WHERE ct.id = OLD.id;
    IF v_start IS NOT NULL AND now() >= v_start THEN RAISE EXCEPTION '開始時刻を過ぎたリハーサルのチケットはキャンセルできません。'; END IF;
  END IF;
  RETURN NEW;
END $$;

GRANT SELECT ON public.rehearsal_round_names TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_official_rehearsal(smallint,text,timestamptz,timestamptz,smallint), public.update_official_rehearsal(smallint,text,timestamptz,timestamptz,smallint), public.delete_or_deactivate_official_rehearsal(smallint), public.issue_rehearsal_ticket_with_code(uuid,smallint,smallint,smallint,smallint,smallint,text[],text[]) TO service_role;
REVOKE ALL ON FUNCTION public.create_official_rehearsal(smallint,text,timestamptz,timestamptz,smallint), public.update_official_rehearsal(smallint,text,timestamptz,timestamptz,smallint), public.delete_or_deactivate_official_rehearsal(smallint), public.issue_rehearsal_ticket_with_code(uuid,smallint,smallint,smallint,smallint,smallint,text[],text[]) FROM anon, authenticated;
