-- チケットを扱わない展示部活の紹介情報。
CREATE TABLE public.exhibition_clubs (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name text NOT NULL UNIQUE,
  description text NOT NULL DEFAULT '',
  image_path text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.organization_admins
  ADD COLUMN exhibition_club_id smallint
    REFERENCES public.exhibition_clubs(id) ON DELETE CASCADE;

ALTER TABLE public.organization_admins
  DROP CONSTRAINT organization_admins_one_performance;

ALTER TABLE public.organization_admins
  ADD CONSTRAINT organization_admins_one_performance CHECK (
    (class_performance_id IS NOT NULL AND gym_performance_id IS NULL AND exhibition_club_id IS NULL) OR
    (class_performance_id IS NULL AND gym_performance_id IS NOT NULL AND exhibition_club_id IS NULL) OR
    (class_performance_id IS NULL AND gym_performance_id IS NULL AND exhibition_club_id IS NOT NULL)
  );

ALTER TABLE public.exhibition_clubs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.exhibition_clubs
  FOR SELECT USING (true);
GRANT SELECT ON public.exhibition_clubs TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.exhibition_clubs_id_seq TO anon, authenticated;
